include /etc/nginx/modules-enabled/*.conf;
user www-data;
worker_processes auto;
pid /run/nginx.pid;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  log_format lab '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent';
  access_log /var/log/nginx/access.log lab;
  error_log /var/log/nginx/error.log warn;
  client_header_timeout 10s;
  client_body_timeout 10s;
  send_timeout 10s;
  keepalive_timeout 10s;
  client_max_body_size 1m;
  server {
    listen 80;
    location / {
      proxy_pass http://keycloak:8080;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_connect_timeout 3s;
      proxy_read_timeout 15s;
    }
  }
}
stream {
  log_format ldaps '$remote_addr [$time_local] $status $session_time';
  access_log /var/log/nginx/ldaps.log ldaps;
  limit_conn_zone $binary_remote_addr zone=ldap_per_ip:10m;
  server {
    listen 636;
    proxy_pass openldap:636;
    proxy_connect_timeout 3s;
    proxy_timeout 10s;
    limit_conn ldap_per_ip 10;
  }
}
